#!/usr/bin/env zsh 
if [ "$1" = "--up" ]; then
    # eww -c $HOME/.dotfiles/eww/bar o bri && brightnessctl -q s 5%+  && sleep 3 &&  eww -c $HOME/.dotfiles/eww/bar c bri
    swayosd-client --brightness raise
elif [ "$1" = "--down" ]; then
    # eww -c $HOME/.dotfiles/eww/bar o bri && brightnessctl -q s 5%- && sleep 3 &&  eww -c $HOME/.dotfiles/eww/bar c bri
    swayosd-client --brightness lower
elif [ "$1" = "--get" ]; then
    echo $(brightnessctl | head -n 2 | tail -n 1 | awk '{print $4}' | tr -d '(%)')
fi
