#!/usr/bin/env zsh
grim -g "$(slurp)" - | satty --filename -  --output-filename ~/Pictures/Screenshots/satty-$(date '+%Y%m%d-%H:%M:%S').png
# grim -g "$(slurp)" - | swappy -f - -o ~/Pictures/Screenshots/swappy-$(date '+%Y%m%d-%H:%M:%S').png
